export const teamsByYear = {
  "2024": [
    "Pittsburgh",
    "Toledo",
    "Rutgers",
    "Kansas State",
    "Arkansas State",
    "Bowling Green",
    "Navy",
    "Oklahoma",
    "Georgia Tech",
    "Vanderbilt",
    "Arkansas",
    "Texas Tech",
    "Syracuse",
    "Washington State",
    "USC",
    "Texas A&M",
    "UConn",
    "North Carolina",
    "Boston College",
    "Nebraska",
    "TCU",
    "Louisiana",
    "Miami",
    "Iowa State",
    "Colorado State",
    "Miami (OH)",
    "NC State",
    "East Carolina",
    "BYU",
    "Colorado",
    "Army",
    "Louisiana Tech",
    "Missouri",
    "Iowa",
    "Alabama",
    "Michigan",
    "Louisville",
    "Washington",
    "South Carolina",
    "Illinois",
    "LSU",
    "Baylor",
    "Ole Miss",
    "Duke",
    "Oregon",
    "Penn State",
    "Boise State",
    "Ohio State",
    "Texas",
    "Notre Dame",
    "Arizona State",
    "Tennessee",
    "Georgia",
    "Indiana",
    "SMU",
    "Clemson"
  ]
};